"""empty message

Revision ID: 3a7b74968153
Revises: 609f22b0ea16
Create Date: 2018-08-30 11:51:17.906477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a7b74968153'
down_revision = '609f22b0ea16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('memberRequest_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['memberRequest_id'], ['memberRequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useraccount_email'), 'useraccount', ['email'], unique=True)
    op.create_index(op.f('ix_useraccount_first_name'), 'useraccount', ['first_name'], unique=False)
    op.create_index(op.f('ix_useraccount_last_name'), 'useraccount', ['last_name'], unique=False)
    op.create_index(op.f('ix_useraccount_username'), 'useraccount', ['username'], unique=True)
    op.drop_table('memberrequest')
    op.add_column('books', sa.Column('isbn', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isbn')
    op.create_table('memberrequest',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('isbn', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_useraccount_username'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_last_name'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_first_name'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_email'), table_name='useraccount')
    op.drop_table('useraccount')
    op.drop_table('memberRequest')
    # ### end Alembic commands ###
