"""empty message

Revision ID: 620cdbefb4ad
Revises: 
Create Date: 2018-08-16 07:00:13.356613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620cdbefb4ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userAccount_email'), 'userAccount', ['email'], unique=True)
    op.create_index(op.f('ix_userAccount_first_name'), 'userAccount', ['first_name'], unique=False)
    op.create_index(op.f('ix_userAccount_last_name'), 'userAccount', ['last_name'], unique=False)
    op.create_index(op.f('ix_userAccount_username'), 'userAccount', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userAccount_username'), table_name='userAccount')
    op.drop_index(op.f('ix_userAccount_last_name'), table_name='userAccount')
    op.drop_index(op.f('ix_userAccount_first_name'), table_name='userAccount')
    op.drop_index(op.f('ix_userAccount_email'), table_name='userAccount')
    op.drop_table('userAccount')
    # ### end Alembic commands ###
